name: Deploy

on:
  push:
    branches:
      - test2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "web-tech-dashboard" #Must be unique in Heroku
          heroku_email: "Taras.Korolchuk.11@knu.ua"